Repository w3c/wcag, pull requests merged in 2019-06, with the labels that each got.

#732 Label in Name Understanindg edits for consistency
  techniques/failures/F96.html
  understanding/21/label-in-name.html
Labels: Ready for publish

#649 general techniques for label in name
  techniques/aria/img/work-phone.png
  techniques/general/G208.html
  techniques/general/G211.html
  techniques/general/img/call-me-radio-button-group.png
  techniques/general/img/new-password.png
  techniques/general/img/rate-response.png
  techniques/general/img/stacked-label.png
  techniques/general/img/value-checkbox.png
  working-examples/label-in-name-general/example1.html
  working-examples/label-in-name-general/example2.html
  working-examples/label-in-name-general/example3.html
  working-examples/label-in-name-general/example4.html
Labels: Ready for publish

#701 In 1.4.11 Understanding text, adds field boundary exception when contrasty placeholder present
  understanding/21/non-text-contrast.html
Labels: Ready for Survey

#690 Failure technique for 2.5.6 Concurrent Input Mechanisms
  techniques/failures/failure-concurrent-input-mechanisms-touch-or-mouse-keyboard.html
Labels: Ready for publish, Techniques, WCAG 2.1

#692 Short cuts addendum
  understanding/21/character-key-shortcuts.html
Labels: Ready for publish, Surveyed - Accepted

#606 corrections to Character key shorts and Reflow
  guidelines/sc/21/character-key-shortcuts.html
  guidelines/sc/21/reflow.html
Labels: Editorial, Errata

#714 Update pointer-gestures understanding doc
  understanding/21/img/path-based-gesture-1.png
  understanding/21/img/path-based-gesture-2.png
  understanding/21/pointer-gestures.html
Labels: Survey - Accepted, Understanding, WCAG 2.1

#726 Technique: Native controls for up event
  techniques/general/G212.html
  understanding/21/pointer-cancellation.html
Labels: Ready for publish, Survey - Accepted

#604 Changes to address Issue #165
  techniques/html/H39.html
Labels: Ready for publish, Survey - Accepted

#769 Remove WAI glossary text on Charter
  charter.html
Labels: WCAG 2.2

#784 Adding security considerations to H98
  techniques/html/H98.html
Labels: Techniques, WCAG 2.1

#669 Technique for device motion actuation
  techniques/general/G213.html
  understanding/21/motion-actuation.html
  working-examples/device-motion-sensor-input/index.html
Labels: Survey - Added, Techniques

#688 Sort out figure labels
  techniques/client-side-script/SCR32.html
  techniques/failures/F69.html
  techniques/flash/FLASH1.html
  techniques/flash/FLASH10.html
  techniques/flash/FLASH15.html
  techniques/flash/FLASH2.html
  techniques/flash/FLASH20.html
  techniques/flash/FLASH21.html
  techniques/flash/FLASH28.html
  techniques/flash/FLASH29.html
  techniques/flash/FLASH32.html
  techniques/flash/FLASH5.html
  techniques/flash/FLASH6.html
  techniques/flash/FLASH8.html
  techniques/general/G162.html
  techniques/general/G167.html
  techniques/general/G175.html
  techniques/general/G209.html
  techniques/general/G211.html
  techniques/general/G56.html
  techniques/pdf/PDF1.html
  techniques/pdf/PDF10.html
  techniques/pdf/PDF11.html
  techniques/pdf/PDF12.html
  techniques/pdf/PDF13.html
  techniques/pdf/PDF15.html
  techniques/pdf/PDF16.html
  techniques/pdf/PDF17.html
  techniques/pdf/PDF18.html
  techniques/pdf/PDF19.html
  techniques/pdf/PDF2.html
  techniques/pdf/PDF20.html
  techniques/pdf/PDF21.html
  techniques/pdf/PDF22.html
  techniques/pdf/PDF23.html
  techniques/pdf/PDF3.html
  techniques/pdf/PDF4.html
  techniques/pdf/PDF5.html
  techniques/pdf/PDF6.html
  techniques/pdf/PDF7.html
  techniques/pdf/PDF8.html
  techniques/pdf/PDF9.html
  techniques/silverlight/SL13.html
  techniques/silverlight/SL15.html
  techniques/silverlight/SL2.html
  techniques/silverlight/SL20.html
  techniques/silverlight/SL23.html
  techniques/silverlight/SL28.html
  techniques/silverlight/SL29.html
  techniques/silverlight/SL35.html
  techniques/silverlight/SL8.html
  understanding/21/content-on-hover-or-focus.html
  understanding/21/label-in-name.html
  understanding/21/non-text-contrast.html
  understanding/21/pointer-gestures.html
  understanding/21/reflow.html
  understanding/21/text-spacing.html
  xslt/base.xslt
Labels: Editorial change

#792 Wcag22 requirements update
  requirements/22/index.html
Labels: WCAG 2.2
