Repository w3c/wcag, pull requests merged in 2020-07, with the labels that each got.

#1158 Findable Help
  guidelines/index.html
  guidelines/sc/22/findable-help.html
  guidelines/terms/22/single-page-apps.html
  techniques/general/G220.html
  understanding/22/findable-help.html
Labels: WCAG 2.2

#1127 WCAG 2.2 Hidden Controls
  guidelines/index.html
  guidelines/sc/22/hidden-controls.html
  techniques/general/hidden-control-1.html
  techniques/general/hidden-control-2.html
  understanding/22/hidden-controls.html
Labels: WCAG 2.2

#1046 WCAG 2.2 Redundant entry
  guidelines/index.html
  guidelines/sc/22/redundant-entry.html
  techniques/general/G221.html
  understanding/22/redundant-entry.html
Labels: WCAG 2.2

#1179 WCAG 2.2 Pointer Target Spacing
  guidelines/index.html
  guidelines/sc/22/pointer-target-spacing.html
  techniques/css/C42.html
  techniques/css/img/pointer-spacing-1.png
  techniques/css/img/pointer-spacing-2.png
  understanding/22/img/pointer-target-example1.png
  understanding/22/img/pointer-target-example2.png
  understanding/22/img/pointer-target-example3.png
  understanding/22/img/pointer-target-example4.png
  understanding/22/img/pointer-target-example5.png
  understanding/22/pointer-target-spacing.html
  working-examples/css-pointer-spacing/index.html
Labels: WCAG 2.2

#1204 Adding fstorr's updates - border note in focus-vis
  understanding/22/focus-appearance-minimum.html
Labels: Survey - Added, Understanding, WCAG 2.2

#1215 Reflow for table cells - Addressing 1129
  guidelines/sc/21/reflow.html
  understanding/21/reflow.html
Labels: 1.4.10 Reflow, Survey - Added, WCAG 2.1, WCAG 2.2
