Repository w3c/wcag, pull requests merged in 2021-12, with the labels that each got.

#2120 Adding suggestions from issue #1965
  understanding/22/accessible-authentication.html
Labels: Survey - Ready for

#2092 Consistent Help understanding and technique edits
  techniques/general/G220.html
  understanding/22/consistent-help.html
Labels: Survey - Added

#2161 Correct example wording for default focus style in 1.4.11 understanding
  understanding/21/non-text-contrast.html
Labels: WCAG 2.1, Understanding, 1.4.11 Non-text contrast
