Repository w3c/wcag, pull requests merged in 2021-01, with the labels that each got.

#1571 Example 2 update.
  understanding/20/sensory-characteristics.html
Labels: WCAG 2.1, WCAG 2.2

#1576 Adding ID's to conformance levels
  guidelines/index.html
Labels: WCAG 2.1, WCAG 2.2

#1501 Focus-appearance 2.4.11 SC & Understanding rewording suggestions
  guidelines/sc/22/focus-appearance-minimum.html
  guidelines/terms/22/perimeter.html
  understanding/22/focus-appearance-minimum.html
Labels: Ready for publish

#1593 4.2.1 typo in Identify Purpose
  understanding/21/identify-purpose.html
Labels: WCAG 2.1

#1376 Issue 1229 Clarity on self-help option
  guidelines/sc/22/findable-help.html
Labels: Survey - Added
