Repository w3c/wcag, pull requests merged in 2021-06, with the labels that each got.

#1569 Changes to 2.5.1 Pointer Gestures understanding
  understanding/21/pointer-gestures.html
Labels: Survey - Ready for, Understanding, WCAG 2.1, WCAG 2.2

#1687 Understanding 1.4.12: clarify the intent and author responsibility
  understanding/21/text-spacing.html
Labels: 1.4.12 text spacing, Survey - Added, Understanding, WCAG 2.1

#1770 Target size understanding review mg
  understanding/22/img/pointer-target-example3-v2.png
  understanding/22/img/pointer-target-example4-v2.png
  understanding/22/target-size-minimum.html
Labels: Survey - Ready for

#1920 Removing wcag22 techniques
  techniques/css/C42.html
  techniques/failures/F108.html
  techniques/general/G218.html
  techniques/general/G219.html
  techniques/general/G220.html
  techniques/general/G221.html
  techniques/general/hidden-control-1.html
  techniques/general/hidden-control-2.html
  techniques/html/H99.html
Labels: WCAG 2.1

#1921 WCAG 2.1 - removing wcag22 understandings
  understanding/21/accessible-authentication.html
  understanding/21/identify-changes.html
  understanding/21/interruptions-minimum.html
  understanding/21/target-size-enhanced.html
Labels: WCAG 2.1

#1568 Expand 3.3.2 Labels or Instructions understanding
  understanding/20/labels-or-instructions.html
Labels: Discussion, Survey - Added, WCAG 2.2

#1938 Switch from Travis CI to GitHub action
  .github/scripts/deploy.sh
  .github/workflows/manual-publish.yml
  .travis.yml
Labels: Tooling
