Repository w3c/wcag, pull requests merged in 2022-03, with the labels that each got.

#2235 Fix typo in Understanding 2.5.3: Label in Name
  understanding/21/label-in-name.html
Labels: WCAG 2.1, Understanding, 2.5.3 Label in Name

#1765 Update changes-of-context.html
  guidelines/terms/20/changes-of-context.html
Labels: WCAG 2.1, Errata

#2240 copy relative luminance to understanding
  build.xml
Labels: WCAG 2.1, WCAG 2.2
