Repository w3c/wcag, pull requests merged in 2023-10, with the labels that each got.

#3436 WCAG 2.2 outdated files cleanup
  understanding/22/page-break-navigation.html
Labels: Editorial, WCAG 2.2

#3467 Update relative-luminance.html add lang attribute
  guidelines/relative-luminance.html
Labels: Editorial, Technical (bug)

#3452 Remove "draft WCAG 2.2" status / link on 2.2 understanding documents
  understanding/22/accessible-authentication-enhanced.html
  understanding/22/accessible-authentication-minimum.html
  understanding/22/consistent-help.html
  understanding/22/dragging-movements.html
  understanding/22/focus-appearance.html
  understanding/22/focus-not-obscured-enhanced.html
  understanding/22/focus-not-obscured-minimum.html
  understanding/22/redundant-entry.html
  understanding/22/target-size-minimum.html
Labels: Editorial, Understanding, WCAG 2.2

#3434 Update SCR28.html remove link to non-existent technique
  techniques/client-side-script/SCR28.html
Labels: Editorial

#3433 Update ARIA17.html to fix broken link
  techniques/aria/ARIA17.html
Labels: Editorial

#3432 Update base.xslt to fix incorrect Chairs email address
  xslt/base.xslt
Labels: Editorial, Technical (bug)

#2507 Minor typo if G181
  techniques/general/G181.html
Labels: Editorial, WCAG 2.1, Techniques, 2.2.1 Timing Adjustable

#2723 Correct typo in 2.1.4 understanding
  understanding/21/character-key-shortcuts.html
Labels: Editorial, WCAG 2.1, Understanding, 2.1.4: Character Key Shortcuts

#3484 Update G78.html - remove broken links
  techniques/general/G78.html
Labels: Editorial, Techniques
