Repository w3c/wcag, pull requests merged in 2023-11, with the labels that each got.

#3528 Fixing "1.4.11 Non-text Contrast" link in SC 2.4.13 Focus Appearance Understanding document - Editorial
  understanding/22/focus-appearance.html
Labels: Editorial

#3525 Update name-role-value.html - replace link to obsolete content
  understanding/20/name-role-value.html
Labels: Technical (bug), Understanding

#3509 Updating "mechanism" term, so anchor in 3.2.6 Consistent Help understanding works - Editorial
  guidelines/terms/20/mechanism.html
Labels: Bug Fixes

#3312 Adding why it is important to 2.1 SCs
  understanding/21/animation-from-interactions.html
  understanding/21/character-key-shortcuts.html
  understanding/21/concurrent-input-mechanisms.html
  understanding/21/content-on-hover-or-focus.html
  understanding/21/identify-input-purpose.html
  understanding/21/identify-purpose.html
  understanding/21/label-in-name.html
  understanding/21/motion-actuation.html
  understanding/21/non-text-contrast.html
  understanding/21/orientation.html
  understanding/21/pointer-cancellation.html
  understanding/21/pointer-gestures.html
  understanding/21/reflow.html
  understanding/21/status-messages.html
  understanding/21/target-size-enhanced.html
  understanding/21/text-spacing.html
  understanding/21/timeouts.html
Labels: Survey - Added, WCAG 2.1
