Repository w3c/wcag, pull requests merged in 2024-11, with the labels that each got.

#4080 Cfc style updates
  guidelines/index.html
  guidelines/input-purposes.html
  guidelines/relative-luminance.html
  guidelines/sc/20/audio-control.html
  guidelines/sc/20/bypass-blocks.html
  guidelines/sc/20/consistent-identification.html
  guidelines/sc/20/consistent-navigation.html
  guidelines/sc/20/error-prevention-all.html
  guidelines/sc/20/error-prevention-legal-financial-data.html
  guidelines/sc/20/focus-order.html
  guidelines/sc/20/language-of-page.html
  guidelines/sc/20/location.html
  guidelines/sc/20/multiple-ways.html
  guidelines/sc/20/name-role-value.html
  guidelines/sc/20/no-keyboard-trap.html
  guidelines/sc/20/pause-stop-hide.html
  guidelines/sc/20/three-flashes-or-below-threshold.html
  guidelines/sc/22/accessible-authentication-minimum.html
  guidelines/sc/22/consistent-help.html
  guidelines/sc/22/focus-not-obscured-minimum.html
  guidelines/terms/20/accessibility-supported.html
  guidelines/terms/20/ambiguous-to-users-in-general.html
  guidelines/terms/20/assistive-technology.html
  guidelines/terms/20/changes-of-context.html
  guidelines/terms/20/conforming-alternate-version.html
  guidelines/terms/20/content.html
  guidelines/terms/20/general-flash-and-red-flash-thresholds.html
  guidelines/terms/20/input-error.html
  guidelines/terms/20/label.html
  guidelines/terms/20/name.html
  guidelines/terms/20/process.html
  guidelines/terms/20/relative-luminance.html
  guidelines/terms/20/same-functionality.html
  guidelines/terms/20/set-of-web-pages.html
  guidelines/terms/20/structure.html
  guidelines/terms/20/supplemental-content.html
  guidelines/terms/20/technology.html
  guidelines/terms/20/user-agent.html
  guidelines/terms/20/web-page.html
  guidelines/terms/21/set-of-web-pages.html
  guidelines/terms/22/cognitive-function-test.html
  guidelines/wcag.json
Labels: Editorial, Normative

#3154 just capitalization fix
  guidelines/sc/20/parsing.html
Labels: Normative, Bug Fixes

#3756 Change <ol> to <ul> when no order is intended (normative)
  guidelines/sc/22/accessible-authentication-minimum.html
  guidelines/terms/20/changes-of-context.html
  guidelines/terms/20/general-flash-and-red-flash-thresholds.html
  guidelines/terms/20/structure.html
Labels: Editorial, ErratumRaised, Normative

#3636 Removing defunct 'encloses' definition
  guidelines/index.html
  guidelines/terms/22/encloses.html
Labels: ErratumRaised, Bug Fixes

#4070 Add "modality" to single pointer definition with examples of single pointer interactions
  guidelines/terms/21/single-pointer.html
Labels: ErratumRaised, Normative

#4123 Update changelog in guidelines/index.html
  guidelines/index.html
Labels: Editorial, Normative

#3938 Fix typo
  guidelines/index.html
Labels: Editorial, Normative

#3189 Editorial update to target size (minimum) exceptions
  guidelines/sc/22/target-size-minimum.html
Labels: Editorial, WCAG 2.2, Normative, 2.5.8 Target Size (Minimum)

#3707 Update used-in-an-unusual-or-restricted-way.html
  guidelines/terms/20/used-in-an-unusual-or-restricted-way.html
Labels: Editorial, ErratumRaised

#3943 Turn "cognitive function test" definition term lowercase
  guidelines/terms/22/cognitive-function-test.html
Labels: Editorial, Normative

#3776 Change "tablets...mobile devices" to a better structure without suggesting tablets AREN'T mobile devices
  guidelines/index.html
Labels: Editorial, ErratumRaised

#3380 Update input-purposes for syntax highlighting
  guidelines/input-purposes.html
Labels: WCAG 2.1, ErratumRaised, WCAG 2.2, Normative, 1.3.5 Identify Input Purpose, Async-Approval, Bug Fixes

#3038 Editorial suggestions for consistent links to definitions and capitalization
  guidelines/sc/20/audio-control.html
  guidelines/sc/20/error-prevention-all.html
  guidelines/sc/20/error-prevention-legal-financial-data.html
  guidelines/sc/20/focus-visible.html
  guidelines/sc/20/language-of-parts.html
  guidelines/sc/20/link-purpose-link-only.html
  guidelines/sc/20/name-role-value.html
  guidelines/sc/20/pause-stop-hide.html
  guidelines/sc/20/reading-level.html
  guidelines/sc/20/timing-adjustable.html
  guidelines/sc/20/visual-presentation.html
  guidelines/sc/21/content-on-hover-or-focus.html
  guidelines/sc/21/non-text-contrast.html
  guidelines/sc/21/reflow.html
  guidelines/sc/21/target-size-enhanced.html
  guidelines/sc/21/text-spacing.html
  guidelines/terms/20/blocks-of-text.html
  guidelines/terms/20/human-language.html
  guidelines/terms/20/image-of-text.html
  guidelines/terms/20/input-error.html
  guidelines/terms/20/non-text-content.html
  guidelines/terms/20/on-a-full-screen-window.html
  guidelines/terms/20/programmatically-set.html
  guidelines/terms/20/text-alternative.html
  guidelines/terms/20/viewport.html
  guidelines/terms/21/region.html
  guidelines/terms/21/state.html
  guidelines/terms/21/status-message.html
  guidelines/terms/21/target.html
  guidelines/terms/21/user-inactivity.html
  guidelines/terms/22/minimum-bounding-box.html
Labels: Editorial, Normative

#1481 Change markers: add New visual style and remove unnecessary "text semantics"
  guidelines/guidelines.css
  script/wcag.js
Labels: Editorial, Survey - Ready for, WCAG 2.1, ErratumRaised, WCAG 2.2

#3362 Update mention of "list" to "list item" in programmatically-determine…
  guidelines/terms/20/programmatically-determined-link-context.html
Labels: ErratumRaised, WCAG 2.0, Normative

#4007 Eleventy build: Support generating WCAG 2.1 docs from main branch
  11ty/CustomLiquid.ts
  11ty/README.md
  11ty/cheerio.ts
  11ty/guidelines.ts
  11ty/techniques.ts
  11ty/understanding.ts
  README.md
  _includes/techniques/changelog/21.html
  _includes/techniques/changelog/22.html
  _includes/wai-site-footer.html
  acknowledgements/ag-contributors.html
  acknowledgements/ag-wg-active.html
  acknowledgements/funders.html
  eleventy.config.ts
  package-lock.json
  package.json
  techniques/index.html
  understanding/20/three-flashes-or-below-threshold.html
  understanding/21/pointer-gestures.html
  understanding/21/target-size-enhanced.html
  understanding/index.html
  understanding/intro.html
  understanding/refer-to-wcag.html
  understanding/understanding-techniques.html
Labels: WCAG 2.1

#4145 Change "NEW" marker to use W3C blue background
  guidelines/guidelines.css
Labels: Bug Fixes

#4012 Add explanation of what "automatic" means in 2.2.2 and 1.4.2, cross-reference
  understanding/20/audio-control.html
  understanding/20/pause-stop-hide.html
  understanding/21/animation-from-interactions.html
Labels: Understanding, WCAG 2.0, 2.3.3 Animation from Interactions, 1.4.2: Audio Control, 2.2.2 Pause stop hide, Substantive

#4155 Pin definitions when building an older version
  11ty/CustomLiquid.ts
  11ty/guidelines.ts
  11ty/types.ts
  eleventy.config.ts
Labels: Bug Fixes
