Repository w3c/wcag, pull requests merged in 2024-09, with the labels that each got.

#3941 Instructions paragraph cleanup
  techniques/aria/ARIA24.html
  techniques/client-side-script/SCR39.html
  techniques/css/C39.html
  techniques/failures/F102.html
  techniques/failures/F105.html
  techniques/failures/F97.html
  techniques/general/G211.html
  techniques/general/G212.html
  techniques/general/G217.html
  techniques/general/G218.html
  techniques/general/G219.html
  techniques/general/G220.html
  techniques/html/H100.html
  understanding/21/animation-from-interactions.html
  understanding/21/identify-changes.html
  understanding/21/interruptions-minimum.html
  understanding/21/label-in-name.html
  understanding/21/pointer-cancellation.html
  understanding/21/target-size-enhanced.html
Labels: Editorial, Techniques, Understanding

#4025 minor punctuation fixes - adding missing commas
  guidelines/sc/21/pointer-cancellation.html
  guidelines/sc/21/pointer-gestures.html
  guidelines/sc/22/dragging-movements.html
  guidelines/sc/22/focus-appearance.html
  understanding/21/non-text-contrast.html
Labels: Editorial

#4020 Fix typo in SCR35
  techniques/client-side-script/SCR35.html
Labels: Bug Fixes

#4009 Remove duplicate links
  techniques/general/G141.html
  techniques/html/H63.html
Labels: Bug Fixes

#3995 Fix mentions to HTML to Platform Accessibility APIs Implementation Guide
  techniques/aria/ARIA5.html
  techniques/aria/ARIA6.html
  techniques/aria/ARIA8.html
  techniques/aria/ARIA9.html
  techniques/failures/F65.html
Labels: Editorial, Bug Fixes

#3996 Fix mention of WAI-ARIA 1.0
  techniques/failures/F59.html
Labels: Editorial

#4004 Replace mentions of IE7
  techniques/general/G142.html
  techniques/general/G156.html
Labels: Editorial

#4031 Update links in 1.3.6 Identify Purpose understanding
  understanding/21/identify-purpose.html
Labels: Editorial, Understanding, 1.3.6 Identify Purpose

#3970 Working examples bug fixes
  techniques/aria/ARIA9.html
  working-examples/aria-alert-identify-errors/index.html
  working-examples/aria-labelledby-time-out-input-concatenated-label/index.html
  working-examples/aria-labelledby-workshop-booking-timetable/index.html
  working-examples/device-motion-sensor-input-failure/index.html
  working-examples/device-motion-sensor-input/index.html
Labels: Bug Fixes, Working Examples

#4017 Change color of the focus indicator to match the description
  understanding/21/img/checkbox-example5.png
Labels: WCAG 2.2, 1.4.11 Non-text contrast, Bug Fixes

#4005 Update HTML5, CSS2, and RFC references
  techniques/css/C18.html
  techniques/css/C22.html
  techniques/failures/F1.html
  techniques/failures/F24.html
  techniques/failures/F4.html
  techniques/failures/F58.html
  techniques/failures/F77.html
  techniques/failures/F93.html
  techniques/general/G112.html
  techniques/general/G138.html
  techniques/general/G204.html
  techniques/html/H57.html
  techniques/html/H58.html
  techniques/server-side-script/SVR1.html
Labels: Bug Fixes

#3951 Update G65.html
  techniques/general/G65.html
  working-examples/breadcrumb-trail/index.html
Labels: Substantive

#4006 Remove the frameset example in G128
  techniques/general/G128.html
Labels: Techniques, Substantive

#4075 Fix link to Understanding Test Rules from techniques pages
  _includes/test-rules.html
Labels: Bug Fixes
