Repository w3c/wcag, pull requests merged in 2025-06, with the labels that each got.

#4323 Update audio-description.html
  guidelines/terms/20/audio-description.html
Labels: ErratumRaised, Non-Normative

#4327 Meeting audio description through narration
  _includes/techniques/changelog/21.html
  _includes/techniques/changelog/22.html
  techniques/general/G226.html
  understanding/20/audio-description-or-media-alternative-prerecorded.html
  understanding/20/audio-description-prerecorded.html
Labels: Techniques, Understanding, 1.2.3 Audio Description or Media Alt (Prerec), 1.2.5 Audio Description (Prerecorded), Substantive

#4367 Add note to 3.3.2 understanding to explain "require" in normative wording
  understanding/20/labels-or-instructions.html
Labels: Editorial, Understanding

#4339 Time based media EO references
  understanding/20/audio-description-or-media-alternative-prerecorded.html
  understanding/20/audio-description-prerecorded.html
  understanding/20/audio-only-and-video-only-prerecorded.html
  understanding/20/captions-prerecorded.html
  understanding/20/media-alternative-prerecorded.html
  understanding/20/sign-language-prerecorded.html
  understanding/20/time-based-media.html
Labels: Editorial, 1.2.x Media SCs

#4424 Update errata/21.html for previous publications
  errata/21.html
Labels: Bug Fixes

#4437 Clean out unused Techniques and Understanding pages/images from gh-pages branch
  techniques/aria/aria-log-role.html
  techniques/css/C41-enhanced.html
  techniques/css/focus-indicator-inner.html
  techniques/css/reflow-url.html
  techniques/failures/413 Failure.html
  techniques/failures/F-dragging.html
  techniques/failures/failure-concurrent-input-mechanisms-touch-or-mouse-keyboard.html
  techniques/general/G-Dragging.html
  techniques/general/G222.html
  techniques/general/Gxxx-highly-visible-focus-indicator.html
  techniques/general/hidden-control-1.html
  techniques/general/hidden-control-2.html
  understanding/accessible-authentication-no-exception.html
  understanding/dragging.html
  understanding/findable-help.html
  understanding/fixed-reference-points.html
  understanding/focus-appearance-enhanced.html
  understanding/focus-appearance-minimum.html
  understanding/focus-not-obscured.html
  understanding/focus-visible-enhanced.html
  understanding/hidden-controls.html
  understanding/img/focus-indicator-checkboxs.png
  understanding/img/focus-indicator-checked.png
  understanding/img/focus-indicator-circle.png
  understanding/img/focus-indicator-extra-outline.png
  understanding/img/focus-indicator-icon.png
  understanding/img/focus-indicator-non-contrast.png
  understanding/img/focus-indicator-ntc-comparison1.png
  understanding/img/focus-indicator-outerline.png
  understanding/img/focus-indicator-star-shadow.png
  understanding/img/focus-indicator-star-with-abutted-line.svg
  understanding/img/focus-indicator-strong-dashed-border.svg
  understanding/img/focus-indicator-strong.png
  understanding/img/focus-indicator-thick-non-contrast.png
  understanding/img/focus-indicator-thick-short-side.png
  understanding/img/focus-indicator-thin-non-contrast.png
  understanding/img/focus-indicator-underline.png
  understanding/img/focus-indicator-weak-dashed-border.svg
  understanding/img/visibe-control-meeting-control-hidden.png
  understanding/img/visible-control-edit-menu-hidden.png
  understanding/page-break-navigation.html
  understanding/pointer-target-spacing.html
  understanding/target-size.html
  understanding/visible-controls.html
Labels: Bug Fixes

#4411 Restore SCR21, marked as obsolete
  techniques/client-side-script/SCR21.html
Labels: Bug Fixes

#4421 fix "equivalent" typo
  techniques/general/G224.html
Labels: Editorial, Bug Fixes

#4430 Update broken link in H99
  techniques/html/H99.html
Labels: Bug Fixes

#4390 Audio description failure technique
  techniques/failures/F113.html
  understanding/20/audio-description-prerecorded.html
Labels: Techniques, 1.2.5 Audio Description (Prerecorded), Substantive

#4359 Remove periods from end of definitions
  guidelines/terms/21/single-pointer.html
  guidelines/terms/22/perimeter.html
Labels: ErratumRaised, Normative

#4040 Amend definition of motion animation to *not* exclude blurring
  guidelines/terms/21/motion-animation.html
Labels: WCAG 2.1, ErratumRaised, 2.3.3 Animation from Interactions, Non-Normative

#4165 Harmonise spelling for "breakpoint"
  guidelines/sc/22/consistent-help.html
Labels: ErratumRaised, 3.2.6 Consistent Help, Non-Normative

#2296 link directly to new supplemental guidance
  guidelines/index.html
Labels: ErratumRaised, Non-Normative
